from __future__ import annotations

import asyncio
import signal
from importlib.metadata import PackageNotFoundError, version as package_version
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table

from .bootstrap import create_enrollment_bundle, decode_bundle, make_script
from .config import LocalConfig, default_paths
from .constants import DEFAULT_CONTROL_PORT
from .crypto import sign
from .models import Job
from .node import PiPyNode
from .protocol import message, request
from .service import install_systemd_service
from .store import StateStore

app = typer.Typer(no_args_is_help=True, help="PiPy self-organizing Raspberry Pi compute fabric")
service_app = typer.Typer(help="Manage the PiPy node service")
app.add_typer(service_app, name="service")
console = Console()


def _version() -> str:
    try:
        return package_version("pipy")
    except PackageNotFoundError:
        return "0.1.0+source"


@app.command()
def version() -> None:
    """Print the installed PiPy version."""
    console.print(_version())


@app.command()
def begin(
    port: int = typer.Option(DEFAULT_CONTROL_PORT, help="TCP control port"),
    wifi_ssid: Optional[str] = typer.Option(None, help="Wi-Fi SSID to provision to admitted nodes"),
    wifi_password: Optional[str] = typer.Option(None, help="Wi-Fi password to provision to admitted nodes"),
) -> None:
    """Start a PiPy node. A never-enrolled node becomes a lone-wolf cluster."""
    async def main() -> None:
        node = PiPyNode(default_paths(), port=port)
        await node.initialize(wifi_ssid=wifi_ssid, wifi_password=wifi_password)
        loop = asyncio.get_running_loop()
        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                loop.add_signal_handler(sig, node.stop_event.set)
            except NotImplementedError:
                pass
        cfg = node.cfg
        state = "cluster member" if cfg.enrolled else "awaiting enrollment"
        console.print(f"PiPy node {cfg.node_id} · {state} · control :{cfg.port}")
        if cfg.enrolled:
            console.print(f"cluster {cfg.cluster_id}")
        try:
            await node.run()
        finally:
            await node.close()
    asyncio.run(main())


@app.command()
def enroll(
    bundle: Optional[str] = typer.Option(None, "--bundle", help="Enrollment bundle generated by an existing PiPy cluster"),
    bundle_file: Optional[Path] = typer.Option(None, "--bundle-file", exists=True, dir_okay=False, readable=True, help="Read the enrollment bundle from a file (preferred for secrets)"),
) -> None:
    """Prepare this installation to join an existing PiPy cluster."""
    if (bundle is None) == (bundle_file is None):
        raise typer.BadParameter("provide exactly one of --bundle or --bundle-file")
    enrollment_bundle = bundle if bundle is not None else bundle_file.read_text(encoding="utf-8").strip()
    if not enrollment_bundle:
        raise typer.BadParameter("enrollment bundle is empty")
    paths = default_paths()
    if paths.config.exists():
        cfg = LocalConfig.load(paths.config)
    else:
        from .bootstrap import ensure_identity
        cfg = ensure_identity(paths, DEFAULT_CONTROL_PORT)
    data = decode_bundle(enrollment_bundle)
    if cfg.enrolled and cfg.cluster_id != data.get("cluster_id"):
        raise typer.BadParameter("this PiPy installation already belongs to another cluster")
    cfg.bootstrap_bundle = enrollment_bundle
    cfg.save(paths.config)
    console.print(f"Enrollment prepared for cluster {data['cluster_id']}")


@app.command(name="makemeapipy")
def make_me_a_pipy(
    output: Path = typer.Option(Path("makemeapipy.sh"), help="Output installer/enrollment script"),
    seed_host: Optional[str] = typer.Option(None, help="Reachable address of this node; BLE discovery remains enabled"),
    source: str = typer.Option("git+https://github.com/kellyjanderson/pipy.git", help="pip install source used by generated script"),
) -> None:
    """Generate a one-use script that turns another Raspberry Pi into a cluster member."""
    paths = default_paths()
    if not paths.config.exists():
        raise typer.BadParameter("run 'pipy begin' once to create the lone-wolf cluster first")
    cfg = LocalConfig.load(paths.config)
    store = StateStore(paths.state_db)
    try:
        enrollment_bundle, token_id = create_enrollment_bundle(store, cfg, seed_host=seed_host)
        output.write_text(make_script(enrollment_bundle, source=source), encoding="utf-8")
        output.chmod(0o700)
    finally:
        store.close()
    console.print(f"Created {output} · one-use enrollment {token_id}")
    console.print("Treat this script as a credential and delete it after successful use.")


@app.command()
def status() -> None:
    """Show local replicated cluster state."""
    paths = default_paths()
    if not paths.config.exists():
        console.print("PiPy has not been initialized")
        raise typer.Exit(1)
    cfg = LocalConfig.load(paths.config)
    store = StateStore(paths.state_db)
    try:
        leader = store.get("leader_id")
        table = Table(title=f"PiPy cluster {cfg.cluster_id or 'unenrolled'}")
        table.add_column("node")
        table.add_column("host")
        table.add_column("state")
        table.add_column("role")
        table.add_column("capacity")
        for member in store.members():
            table.add_row(member.node_id, f"{member.host}:{member.port}", str(member.status), "leader" if member.node_id == leader else "member", f"{member.capacity:.3f}")
        console.print(table)
        for job in store.jobs():
            work = store.work(job.job_id)
            done = sum(1 for unit in work if unit.status == "complete")
            console.print(f"{job.job_id} {job.kind} {job.status} {done}/{len(work)}")
            if job.result:
                console.print(job.result)
    finally:
        store.close()


@app.command()
def run(
    job: str = typer.Argument(..., help="Job type; MVP provides 'pi'"),
    digits: int = typer.Option(1000, min=1, help="Digits after decimal for the pi workload"),
    wait: bool = typer.Option(True, help="Wait for the job to complete"),
) -> None:
    """Submit a distributed job through the running PiPy cluster."""
    async def main() -> None:
        paths = default_paths()
        if not paths.config.exists():
            raise RuntimeError("PiPy has not been initialized")
        cfg = LocalConfig.load(paths.config)
        if not cfg.enrolled:
            raise RuntimeError("this node is not part of a PiPy cluster")
        store = StateStore(paths.state_db)
        try:
            leader_id = store.get("leader_id")
            leader = next((member for member in store.members() if member.node_id == leader_id), None)
            if leader is None:
                raise RuntimeError("cluster has no known leader")
            body = message("submit_job", node_id=cfg.node_id, job_kind=job, parameters={"digits": digits})
            body["signature"] = sign(cfg.node_private, {key: value for key, value in body.items() if key != "signature"})
            response = await request(leader.host, leader.port, body, timeout=10.0)
            if response.get("kind") == "redirect" and response.get("leader"):
                target = response["leader"]
                response = await request(target["host"], int(target["port"]), body, timeout=10.0)
            if response.get("kind") != "job_submitted":
                raise RuntimeError(response.get("error", "job submission failed"))
            job_id = response["job"]["job_id"]
            console.print(f"submitted {job_id}")
            if not wait:
                return
            while True:
                current = store.job(job_id)
                if current and current.status == "complete":
                    console.print(current.result)
                    return
                if current and current.status == "failed":
                    raise RuntimeError(current.error or "job failed")
                query = await request(leader.host, leader.port, message("job_status", job_id=job_id), timeout=2.0)
                if query.get("job"):
                    current = Job(**query["job"])
                    store.put_job(current)
                    if current.status == "complete":
                        console.print(current.result)
                        return
                await asyncio.sleep(0.5)
        finally:
            store.close()
    asyncio.run(main())


@service_app.command("install")
def service_install(start: bool = typer.Option(False, "--start", help="Start/restart the service after installation")) -> None:
    unit = install_systemd_service(start=start)
    console.print(f"installed {unit}")
