"""Frozen PiPy node-name corpus.

Dataset version 1 is intentionally immutable. Changing these ordered tuples would
rename existing nodes. Add a new dataset version instead.

The corpus was curated from public biographical indexes of mathematicians,
computer scientists, statisticians, logicians, cryptographers, and closely
related theoretical physicists. See NODE_NAMES.md for provenance and policy.
"""

NODE_NAME_DATASET_VERSION = 1

GIVEN_NAMES: tuple[str, ...] = (
    'Abdus', 'Abraham', 'Ada', 'Adele', 'Adi', 'Adrien-Marie', 'Akshay',
    'Al-Biruni', 'Al-Khwarizmi', 'Al-Kindi', 'Alan', 'Albert', 'Aleksandr',
    'Alessio', 'Alex', 'Alexander', 'Alfred', 'Alice', 'Allen', 'Alonzo',
    'Anders', 'Andrea', 'Andrew', 'Andrey', 'André', 'Anita', 'Annie',
    'Antoni', 'Apollonius', 'Archimedes', 'Arthur', 'Artur', 'Aryabhata',
    'Atle', 'August', 'Augustin', 'Augustin-Louis', 'Augustus', 'Avi',
    'Barbara', 'Barry', 'Ben', 'Benoit', 'Beppo', 'Bernhard', 'Betty',
    'Bhama', 'Bhaskara', 'Bill', 'Bjarne', 'Blaise', 'Bob', 'Bradley',
    'Brahmagupta', 'Brendan', 'Brian', 'Bronisław', 'Brook', 'Butler', 'Béla',
    'Calyampudi', 'Camille', 'Carl', 'Carlo', 'Caroline', 'Cathleen', 'Caucher',
    'Cecilia', 'Charles', 'Chen-Ning', 'Chien-Shiung', 'Christiaan', 'Christine',
    'Christopher', 'Christos', 'Chuck', 'Claire', 'Claude', 'Colin', 'Corrado',
    'Cumrun', 'Cynthia', 'Cédric', 'Dan', 'Dana', 'Daniel', 'Daniela', 'Daphne',
    'Dario', 'Dattatreya', 'David', 'Debabrata', 'Demis', 'Dennis', 'Diophantus',
    'Dmitri', 'Don', 'Donald', 'Donna', 'Dorothy', 'Douglas', 'Dusa', 'Edgar',
    'Edsger', 'Edward', 'Egon', 'Elon', 'Emmy', 'Endre', 'Enrico', 'Erich',
    'Ernst', 'Erwin', 'Euclid', 'Eugene', 'Eugenio', 'Euphemia', 'Evelyn',
    'Federigo', 'Fei-Fei', 'Felix', 'Fibonacci', 'Florence', 'Frances',
    'Francesco', 'Frank', 'François', 'Fred', 'Frederic', 'Freeman', 'Friedrich',
    'Galileo', 'Garrett', 'Gary', 'Gaspard', 'Gene', 'Geoffrey', 'Georg', 'George',
    'Gerald', 'Gerard', 'Gerd', 'Gerolamo', 'Gilles', 'Girard', 'Giuseppe',
    'Gladys', 'Godfrey', 'Gordon', 'Gottfried', 'Grace', 'Gregorio', 'Grigori',
    'Guido', 'Guillaume', 'Hal', 'Hanna', 'Harald', 'Harish-Chandra', 'Harlan',
    'Hassler', 'Helena', 'Hendrik', 'Henri', 'Henrietta', 'Henry', 'Herbert',
    'Hermann', 'Hilda', 'Hugo', 'Hypatia', 'Ian', 'Ibn', 'Ilya', 'Ingrid',
    'Isaac', 'Isadore', 'Israel', 'Ivan', 'Jack', 'Jacob', 'Jagadish', 'Jakob',
    'James', 'Jean', 'Jean-Baptiste', 'Jean-Pierre', 'Jean-Victor', 'Jeannette',
    'Jef', 'Jeffrey', 'Jerome', 'Jerzy', 'Jim', 'Joan', 'Jocelyn', 'Johann',
    'Johannes', 'John', 'Joseph', 'Joseph-Louis', 'Josiah', 'Juan', 'Judea',
    'Julia', 'Julian', 'Julius', 'June', 'János', 'Jürgen', 'Karen', 'Karl',
    'Karol', 'Katherine', 'Kathleen', 'Kazimierz', 'Ken', 'Kip', 'Klaus',
    'Kunihiko', 'Kurt', 'Larry', 'Laurent', 'Lee', 'Leo', 'Leonard', 'Leonhard',
    'Leonid', 'Leopold', 'Leslie', 'Lev', 'Linus', 'Lisa', 'Lise', 'Louis', 'Lov',
    'Luca', 'Lucien', 'Ludwig', 'Luigi', 'Luis', 'Luitzen', 'Lydia', 'László',
    'Madhava', 'Madhu', 'Manindra', 'Manjul', 'Manuel', 'Manuela', 'Margaret',
    'Maria', 'Marina', 'Marjorie', 'Mark', 'Marshall', 'Marston', 'Martin',
    'Martinus', 'Marvin', 'Mary', 'Maryam', 'Maurice', 'Max', 'Maxim', 'Meghnad',
    'Melanie', 'Michael', 'Michel', 'Mikhail', 'Miklós', 'Mildred', 'Mina', 'Moni',
    'Murray', 'Nalini', 'Nancy', 'Narendra', 'Nasir', 'Neena', 'Ngô', 'Niccolò',
    'Nicolas', 'Nicole', 'Niels', 'Niklaus', 'Nikolai', 'Nilakantha', 'Nils',
    'Nima', 'Noam', 'Noga', 'Norbert', 'Oded', 'Olga', 'Oliver', 'Omar', 'Oscar',
    'Pafnuty', 'Patrick', 'Paul', 'Persi', 'Peter', 'Pierre', 'Pierre-Simon',
    'Prasanta', 'Pythagoras', 'Radia', 'Rafael', 'Rainer', 'Raj', 'Rajeev', 'Ralph',
    'Raman', 'Randy', 'Raoul', 'Rediet', 'René', 'Richard', 'Rob', 'Robert', 'Robin',
    'Rodney', 'Roger', 'Ron', 'Ronald', 'Rose', 'Rudolf', 'Ruth', 'Ruzena', 'Rózsa',
    'Sabine', 'Salil', 'Salvatore', 'Samson', 'Samuel', 'Sanjeev', 'Satyendra',
    'Saunders', 'Scott', 'Sepp', 'Serge', 'Sergei', 'Sergey', 'Seymour', 'Shafi',
    'Shakuntala', 'Shankar', 'Sheldon', 'Shiing-Shen', 'Shing-Tung', 'Silvio',
    'Simon', 'Siméon', 'Sofia', 'Solomon', 'Sophie', 'Sophus', 'Srinivasa',
    'Stanislav', 'Stanislaw', 'Stanisław', 'Stefan', 'Stephen', 'Steve', 'Steven',
    'Stuart', 'Subhash', 'Subrahmanyam', 'Subrahmanyan', 'Susan', 'Svetlana',
    'Taher', 'Takeo', 'Ted', 'Terence', 'Terry', 'Thabit', 'Thales', 'Thomas',
    'Thoralf', 'Tibor', 'Tim', 'Tjalling', 'Tom', 'Tommy', 'Tony', 'Trevor',
    'Tsung-Dao', 'Tullio', 'Umesh', 'Valerie', 'Vaughan', 'Vera', 'Vijay', 'Vint',
    'Vito', 'Vladimir', 'Wacław', 'Walter', 'Warren', 'Watts', 'Wendelin', 'Werner',
    'Whitfield', 'William', 'Wolfgang', 'Yakov', 'Yann', 'Yoshua', 'Élie', 'Évariste',
)

SURNAMES: tuple[str, ...] = (
    'Aaronson', 'Abebe', 'Abel', 'Abelson', 'Abiteboul', 'Abramsky', 'Adleman',
    'Agrawal', 'Ahn', 'Aho', 'al-Haytham', 'al-Tusi', 'Aleksandrov', 'Allen',
    'Alon', 'Amdahl', 'Amodei', 'Anantharaman', 'Arkani-Hamed', 'Arnold', 'Arora',
    'Atiyah', 'Atkinson', 'Avila', 'Backus', 'Bajcsy', 'Baker', 'Ball', 'Banach',
    'Baran', 'Barish', 'Barrow', 'Bartlett', 'Basu', 'Bayes', 'Bell', 'Bellman',
    'Beltrami', 'Bengio', 'Bennett', 'Berge', 'Berners-Lee', 'Bernoulli',
    'Bernstein', 'Bertrand', 'Bhargava', 'Bianchi', 'Birkar', 'Birkhoff',
    'Blackwell', 'Blum', 'Boehm', 'Bohm', 'Bohr', 'Bollobás', 'Boltzmann', 'Bolyai',
    'Bombelli', 'Bombieri', 'Boole', 'Booth', 'Borcherds', 'Borg', 'Borsuk', 'Bose',
    'Bott', 'Bourgain', 'Box', 'Brassard', 'Breazeal', 'Breiman', 'Bricklin',
    'Briggs', 'Brin', 'Brooks', 'Brouwer', 'Browne', 'Bryant', 'Burnell', 'Cam',
    'Cantor', 'Cardano', 'Carmack', 'Cartan', 'Cartwright', 'Cauchy', 'Cayley',
    'Cerf', 'Chandrasekhar', 'Chasles', 'Chebyshev', 'Chern', 'Chomsky', 'Chuquet',
    'Church', 'Châu', 'Clarke', 'Cocke', 'Codd', 'Conway', 'Cook', 'Cooper',
    'Courant', 'Cox', 'Cramér', 'Cray', "d'Alembert", 'Dantzig', 'Darden',
    'Daubechies', 'Davies', 'Dayhoff', 'Dedekind', 'Deligne', 'DeMarco', 'Desargues',
    'Descartes', 'Deutsch', 'Devi', 'Diaconis', 'Dieudonné', 'Diffie', 'Dijkstra',
    'Dirac', 'Dirichlet', 'Donaldson', 'Dresselhaus', 'Duminil-Copin', 'Dwork',
    'Dyson', 'Easley', 'Edmonds', 'Efron', 'Egorov', 'Eich', 'Eilenberg', 'Einstein',
    'Elgamal', 'Engelbart', 'Enriques', 'Erdős', 'Euler', 'Faltings', 'Faraday',
    'Feigenbaum', 'Fermat', 'Fermi', 'Feynman', 'Figalli', 'Fisher', 'Flowers',
    'Fourier', 'Fraenkel', 'Frankston', 'Freedman', 'Friedman', 'Fubini', 'Furber',
    'Galilei', 'Galois', 'Gardner', 'Gauss', 'Geiringer', 'Gelfand', 'Gelfond',
    'Gell-Mann', 'Germain', 'Ghez', 'Gibbs', 'Glashow', 'Goldreich', 'Goldstine',
    'Goldwasser', 'Goodfellow', 'Gosling', 'Gosset', 'Graham', 'Granville',
    'Grassmann', 'Gray', 'Green', 'Grothendieck', 'Grover', 'Gupta', 'Gödel',
    'Hairer', 'Hald', 'Halmos', 'Hamilton', 'Hamming', 'Hardy', 'Hassabis', 'Hastie',
    'Hausdorff', 'Hauser', 'Hawking', 'Haynes', 'Heaviside', 'Heisenberg',
    'Hejlsberg', 'Hellman', 'Hennessy', 'Hermite', 'Hilbert', 'Hinton', 'Hirzebruch',
    'Hoare', 'Hochreiter', 'Holberton', 'Holland', 'Hooft', 'Hopcroft', 'Hopper',
    'Hossenfelder', 'Huh', 'Humphrey', 'Huygens', 'Jackson', 'Jacobi', 'Jitomirskaya',
    'Johnson', 'Jones', 'Jordan', 'Kac', 'Kahn', 'Kalman', 'Kanade', 'Kantorovich',
    'Kaprekar', 'Kare', 'Karmarkar', 'Karp', 'Kavraki', 'Kay', 'Keller', 'Kemeny',
    'Kepler', 'Kernighan', 'Khayyam', 'Khinchin', 'Khot', 'Kilburn', 'Kildall',
    'Kirwan', 'Klein', 'Kleinrock', 'Knaster', 'Knuth', 'Kodaira', 'Koller',
    'Kolmogorov', 'Kontsevich', 'Koopmans', 'Kovalevskaya', 'Koza', 'Krizhevsky',
    'Kronecker', 'Kuratowski', 'Kurtz', "l'Hôpital", 'Laczkovich', 'Ladyzhenskaya',
    'Lafforgue', 'Lagrange', 'Lamport', 'Lampson', 'Landau', 'Lane', 'Lang', 'Laplace',
    'Lavrentiev', 'Leavitt', 'LeCun', 'Lee', 'Lefschetz', 'Legendre', 'Lehmann',
    'Leibniz', 'Leray', 'Levi', 'Levi-Civita', 'Li', 'Lie', 'Lindenstrauss',
    'Liouville', 'Liskov', 'Littlewood', 'Lobachevsky', 'Lorentz', 'Lovelace',
    'Lovász', 'Luzin', 'Lyapunov', 'Maclaurin', 'Mahalanobis', 'Maldacena',
    'Mandelbrot', 'Markov', 'Maxwell', 'Mayer', 'Mazur', 'McCarthy', 'McCulloch',
    'McDuff', 'McIlroy', 'Meitner', 'Merkle', 'Metcalfe', 'Micali', 'Michie', 'Mills',
    'Milner', 'Milnor', 'Minkowski', 'Minsky', 'Mirzakhani', 'Molnár', 'Monge',
    'Morawetz', 'Mordell', 'Morgan', 'Morse', 'Motwani', 'Moufang', 'Möbius', 'Naor',
    'Napier', 'Nash', 'Naur', 'Nelder', 'Nelson', 'Neumann', 'Newell', 'Newman',
    'Newton', 'Neyman', 'Ng', 'Nielsen', 'Nightingale', 'Nilsson', 'Noether', 'Norman',
    'Norvig', "O'Keefe", 'Ollerenshaw', 'Oresme', 'Ousterhout', 'Page',
    'Papadimitriou', 'Papert', 'Parimala', 'Parnas', 'Pascal', 'Patterson', 'Pauli',
    'Payne-Gaposchkin', 'Peano', 'Pearl', 'Pearson', 'Penrose', 'Perelman', 'Perlman',
    'Pike', 'Pincherle', 'Pitts', 'Planck', 'Plücker', 'Poincaré', 'Poisson',
    'Poncelet', 'Pontryagin', 'Péter', 'Pólya', 'Qurra', 'Rabin', 'Radó', 'Raman',
    'Ramanujan', 'Randall', 'Rao', 'Rasiowa', 'Raskin', 'Ratner', 'Reddy', 'Rees',
    'Rham', 'Ribet', 'Ricci-Curbastro', 'Riemann', 'Ritchie', 'Rivest', 'Roberval',
    'Robinson', 'Roman', 'Rosenblatt', 'Ross', 'Rossum', 'Rotblat', 'Roth', 'Rovelli',
    'Rubin', 'Rumelhart', 'Rus', 'Russell', 'Saha', 'Salam', 'Sammet', 'Sarnak',
    'Sastry', 'Schmidhuber', 'Scholze', 'Schrödinger', 'Schwinger', 'Scott',
    'Sedgewick', 'Segre', 'Sejnowski', 'Selberg', 'Series', 'Serre', 'Severi', 'Shamir',
    'Shannon', 'Shneiderman', 'Shor', 'Sierpiński', 'Simon', 'Sinai', 'Singer',
    'Sipser', 'Skolem', 'Smale', 'Smirnov', 'Smolin', 'Sobolev', 'Somayaji',
    'Srinivasan', 'Stallman', 'Steinhaus', 'Stokes', 'Stone', 'Stonebraker', 'Strachey',
    'Strickland', 'Stroustrup', 'Sudan', 'Sullivan', 'Susskind', 'Sutherland',
    'Sutskever', 'Sylvester', 'Szemerédi', 'Tao', 'Tarjan', 'Tarski', 'Tartaglia',
    'Taussky-Todd', 'Taylor', 'Thacker', 'Thom', 'Thomas', 'Thompson', 'Thorne',
    'Thurston', 'Tibshirani', 'Torvalds', 'Trevisan', 'Tukey', 'Turing', 'Turán',
    'Uhlenbeck', 'Ulam', 'Ullman', 'Vadhan', 'Vafa', 'Valiant', 'Vaughan', 'Vazirani',
    'Veloso', 'Veltman', 'Venkatesh', 'Veronese', 'Villani', 'Viète', 'Voisin',
    'Volterra', 'Wald', 'Weierstrass', 'Weil', 'Weinberg', 'Weiss', 'Weizenbaum',
    'Werner', 'West', 'Weyl', 'Wheeler', 'Whitney', 'Wiener', 'Wigderson', 'Wigner',
    'Wiles', 'Wilkes', 'Wilks', 'Williams', 'Wilson', 'Wing', 'Winograd', 'Winston',
    'Wirth', 'Witten', 'Wood', 'Wu', 'Yang', 'Yao', 'Yau', 'Zariski', 'Zermelo',
    'Zygmund', 'Łoś',
)
